/**
 * Copies the example applications into src/generated/examples.ts.
 *
 * The model file (RECIPE) carries one complete application per shape, and the
 * MCP server and the website both read RECIPE — neither can read examples/ at
 * run time (the server ships without it, the site builds in a browser bundle).
 * So the examples are copied into a module, and the copy is held to the
 * directories by `--check`, which tests/rules.spec.ts runs: an example edited
 * without regenerating fails a test instead of teaching a model yesterday's
 * version.
 *
 *   node scripts/build-docs.mjs          write src/generated/examples.ts
 *   node scripts/build-docs.mjs --check  exit 1 if it is out of date
 */
import { existsSync, mkdirSync, readFileSync, readdirSync, writeFileSync } from "node:fs";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const repo = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const target = join(repo, "src", "generated", "examples.ts");

/** The examples the model file carries, one per shape that has one. */
export const EXAMPLES = [
  { shape: "solo", dir: "examples/packing-list", name: "Beach trip" },
  { shape: "passable", dir: "examples/receipts", name: "Receipts" },
  { shape: "session", dir: "examples/tic-tac-toe", name: "Tic-tac-toe" },
];

/** Files in the order a reader wants them: the decision first, then the page. */
const ORDER = ["schema.sql", "index.html", "app.js", "app.css", "icon.svg"];

function filesOf(dir) {
  const absolute = join(repo, dir);
  const names = readdirSync(absolute).filter((name) => ORDER.includes(name));
  names.sort((a, b) => ORDER.indexOf(a) - ORDER.indexOf(b));
  const files = {};
  for (const name of names) {
    // Line endings normalized, so a checkout with CRLF produces the same module.
    files[name] = readFileSync(join(absolute, name), "utf8").replace(/\r\n/g, "\n");
  }
  return files;
}

export function render() {
  const examples = EXAMPLES.map((example) => ({ ...example, files: filesOf(example.dir) }));
  return (
    "// Generated by scripts/build-docs.mjs from examples/. Do not edit by hand:\n" +
    "// change the example, then run `node scripts/build-docs.mjs`.\n\n" +
    "export interface ExampleApp {\n" +
    '  shape: "solo" | "passable" | "session";\n' +
    "  dir: string;\n" +
    "  name: string;\n" +
    "  files: Record<string, string>;\n" +
    "}\n\n" +
    `export const EXAMPLE_APPS: readonly ExampleApp[] = ${JSON.stringify(examples, null, 2)};\n`
  );
}

if (process.argv[1] && resolve(process.argv[1]) === fileURLToPath(import.meta.url)) {
  const next = render();
  if (process.argv.includes("--check")) {
    const current = existsSync(target) ? readFileSync(target, "utf8").replace(/\r\n/g, "\n") : "";
    if (current !== next) {
      process.stderr.write("src/generated/examples.ts is out of date: run node scripts/build-docs.mjs\n");
      process.exit(1);
    }
    process.stdout.write("src/generated/examples.ts is current\n");
  } else {
    mkdirSync(dirname(target), { recursive: true });
    writeFileSync(target, next);
    process.stdout.write(`wrote ${target}\n`);
  }
}
