/**
 * Writes everything the documentation generates from one source.
 *
 *   src/generated/examples.ts          the example applications, for the model file
 *   website/docs/constraints.md         every constraint, by id           (from src/rules.ts)
 *   website/docs/runtime-api.md         the surface an application gets  (from src/rules.ts)
 *   website/docs/schema-reference.md    markers, views, system tables    (from src/rules.ts)
 *   website/docs/refusals.md            refusals an application meets   (from src/rules.ts)
 *   website/docs/parts/shapes.md        the shape decision, included by Choose a shape
 *   website/docs/parts/constraint/*.md  one constraint each, included by the how-to pages
 *
 * Why generate rather than write: the model file (RECIPE) is rendered from the
 * same source, so a page written by hand would be a second copy — and two copies
 * is how the recipe fell behind the code. And why markdown rather than a Vue
 * component rendering at page load: the site's search indexes markdown, and a
 * person has to be able to find one rule without reading everything.
 *
 * The model file cannot read examples/ at run time (the MCP server ships
 * without it, the site builds in a browser bundle), so the examples are copied
 * into a module too. Every output is committed and held to its source by
 * `--check`, which tests/rules.spec.ts runs.
 *
 *   node scripts/build-docs.mjs          write everything
 *   node scripts/build-docs.mjs --check  exit 1 if anything is out of date
 */
import { existsSync, mkdirSync, readFileSync, readdirSync, rmSync, writeFileSync } from "node:fs";
import { dirname, join, relative, resolve } from "node:path";
import { fileURLToPath, pathToFileURL } from "node:url";

const repo = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const GITHUB = "https://github.com/dynamicapplicationinterface/dai-core/blob/main/";
const CONSTRAINT_PARTS = join(repo, "website", "docs", "parts", "constraint");

// Node strips the types from rules.ts as it loads it; the file has no imports.
const rules = await import(pathToFileURL(join(repo, "src", "rules.ts")).href);
const { APP_REFUSALS, CONSTRAINTS, CSS_VARS, MARKERS, SHAPES, SHAPE_DECISION, SHAPE_ORDER, SURFACE, TOPICS, VIEWS } =
  rules;

/* ---------------------------------------------------------- examples */

/** The examples the model file carries, one per shape that has one. */
export const EXAMPLES = [
  { shape: "solo", dir: "examples/packing-list", name: "Beach trip" },
  { shape: "passable", dir: "examples/receipts", name: "Receipts" },
  { shape: "session", dir: "examples/tic-tac-toe", name: "Tic-tac-toe" },
];

/** Files in the order a reader wants them: the decision first, then the page. */
const ORDER = ["schema.sql", "index.html", "app.js", "app.css", "icon.svg"];

function filesOf(dir) {
  const absolute = join(repo, dir);
  const names = readdirSync(absolute).filter((name) => ORDER.includes(name));
  names.sort((a, b) => ORDER.indexOf(a) - ORDER.indexOf(b));
  const files = {};
  for (const name of names) {
    // Line endings normalized, so a checkout with CRLF produces the same module.
    files[name] = readFileSync(join(absolute, name), "utf8").replace(/\r\n/g, "\n");
  }
  return files;
}

function examplesModule() {
  const examples = EXAMPLES.map((example) => ({ ...example, files: filesOf(example.dir) }));
  return (
    "// Generated by scripts/build-docs.mjs from examples/. Do not edit by hand:\n" +
    "// change the example, then run `node scripts/build-docs.mjs`.\n\n" +
    "export interface ExampleApp {\n" +
    '  shape: "solo" | "passable" | "session";\n' +
    "  dir: string;\n" +
    "  name: string;\n" +
    "  files: Record<string, string>;\n" +
    "}\n\n" +
    `export const EXAMPLE_APPS: readonly ExampleApp[] = ${JSON.stringify(examples, null, 2)};\n`
  );
}

/* ---------------------------------------------------------- markdown */

const GENERATED = "<!-- Generated by scripts/build-docs.mjs from src/rules.ts. Do not edit: change src/rules.ts. -->";

/**
 * Text from rules.ts, made safe for a VitePress page.
 *
 * Outside inline code, `<` would open a Vue element, `{{` a Vue expression, and
 * `_` or `*` an emphasis; inside inline code everything is literal already. A
 * text with an unbalanced backtick would silently swallow the rest of the
 * paragraph into code, so it is refused.
 */
function md(text) {
  const ticks = (text.match(/`/g) ?? []).length;
  if (ticks % 2 !== 0) throw new Error(`Unbalanced backtick in: ${text.slice(0, 80)}…`);
  return text
    .split(/(`[^`]*`)/)
    .map((part, index) =>
      index % 2 === 1
        ? part
        : part
            .replace(/&/g, "&amp;")
            .replace(/</g, "&lt;")
            .replace(/>/g, "&gt;")
            .replace(/\{\{/g, "&#123;&#123;")
            .replace(/([_*])/g, "\\$1"),
    )
    .join("");
}

/**
 * A heading. Headings are also copied raw into the permalink's aria-label, so
 * a backslash escape would be read aloud; a word holding an underscore is set
 * as code instead, which is what those words (_r_, t_current) are anyway.
 */
function title(text) {
  const coded = text
    .split(/(`[^`]*`)/)
    .map((part, index) => (index % 2 === 1 ? part : part.replace(/[^\s`]*_[^\s`]*/g, (word) => `\`${word}\``)))
    .join("");
  return md(coded);
}

function shapesOf(shapes) {
  return shapes.length === SHAPE_ORDER.length ? "every shape" : shapes.join(", ");
}

function enforcementOf(constraint) {
  return constraint.enforced
    .map((how) =>
      how === "lint"
        ? `checked by the lint (${(constraint.lint ?? []).map((id) => `\`${id}\``).join(", ")})`
        : how === "compiler"
          ? "refused at build"
          : how === "runtime"
            ? "refused at run time"
            : "not checked by anything",
    )
    .join("; ");
}

function anchorsOf(constraint) {
  const files = [...new Set(constraint.anchors.map((a) => a.file))];
  return files.map((file) => `[\`${file}\`](${GITHUB}${file})`).join(", ");
}

function constraintsPage() {
  const index = SHAPE_ORDER.map((shape) => {
    const ids = CONSTRAINTS.filter((c) => c.shapes.includes(shape)).map((c) => `[${c.id}](#${c.id})`);
    return `- **${shape}** — ${ids.join(" · ")}`;
  }).join("\n");

  const sections = TOPICS.map((topic) => {
    const inTopic = CONSTRAINTS.filter((c) => c.topic === topic.id);
    if (inTopic.length === 0) return "";
    const entries = inTopic
      .map(
        (c) =>
          `### ${c.id} · ${title(c.title)} {#${c.id}}\n\n` +
          `**Applies to** ${shapesOf(c.shapes)}. **Enforcement:** ${enforcementOf(c)}.\n\n` +
          `${md(c.rule)}\n\n` +
          `**Why.** ${md(c.why)}\n\n` +
          `<small>Depends on ${anchorsOf(c)}.</small>`,
      )
      .join("\n\n");
    return `## ${title(topic.title)} {#topic-${topic.id}}\n\n${entries}`;
  })
    .filter(Boolean)
    .join("\n\n");

  return `---
title: Constraints
outline: [2, 3]
---

${GENERATED}

# Constraints

Every rule an application inside a container must follow, each with the reason
it exists and what enforces it. The id is permanent: it is this page's anchor,
it is what a \`dai check\` finding cites, and it is how the [model
file](/docs/the-recipe) names the same rule — the model file is generated from
the same source as this page.

**Enforcement** says what refuses a violation: the compiler at build, the
runtime when the application runs, or the lint (\`dai check\`, the MCP server
and the paste page). "Not checked by anything" is stated plainly so nobody
assumes a check exists that does not; those constraints are still constraints.

Which apply to you depends on the shape — [Choose a shape](/docs/choose-a-shape)
first.

## By shape

${index}

${sections}
`;
}

function runtimeApiPage() {
  const groups = [
    { title: "Every application", test: (s) => s.length === SHAPE_ORDER.length },
    { title: "Shared tables (passable and session)", test: (s) => s.includes("passable") },
    { title: "Sessions", test: (s) => s.length === 1 && s[0] === "session" },
  ];
  const body = groups
    .map((group) => {
      const entries = SURFACE.filter((entry) => group.test(entry.shapes))
        .map((entry) => `- \`${entry.call}\` — ${md(entry.does)}`)
        .join("\n");
      return `## ${group.title}\n\n${entries}`;
    })
    .join("\n\n");
  const vars = CSS_VARS.map((v) => `- \`${v.name}\` — ${md(v.is)}`).join("\n");
  return `---
title: Runtime API
---

${GENERATED}

# Runtime API

Everything an application is given, and nothing else. Each call is checked
against the runtime that defines it by \`tests/rules.spec.ts\`.

${body}

## Custom properties

The host sets these on the application's root so it can paint to the edge of a
phone's screen and keep content clear of what covers it
([EDGE-TO-EDGE](/docs/constraints#EDGE-TO-EDGE)). Zero on a screen with nothing
in the way.

${vars}
`;
}

function schemaPage() {
  const markers = MARKERS.map(
    (m) => `### \`${m.marker}\`\n\n**Where:** ${md(m.where)}\n\n**Does:** ${md(m.does)}`,
  ).join("\n\n");
  const views = VIEWS.map(
    (v) => `### \`${v.name}\`\n\n**Applies to** ${shapesOf(v.shapes)}. ${md(v.holds)}\n\n${md(v.read)}`,
  ).join("\n\n");
  return `---
title: Schema
---

${GENERATED}

# Schema

What \`schema.sql\` declares for sharing, and what the compiler creates from it.
For a replicated table \`t\`, the rewrite adds the replication columns, a key,
the triggers that make it append-only, and the views below. Why it works this
way: [Why rows never change](/docs/why-rows-never-change).

## Markers

${markers}

## Views and system tables

${views}
`;
}

function refusalsPage() {
  const idOf = (code) => code.replace(/[^A-Za-z0-9_-]+/g, "-").replace(/-+$/, "");
  const entries = APP_REFUSALS.map(
    (r) =>
      `### \`${r.code}\` {#${idOf(r.code)}}\n\n**Applies to** ${shapesOf(r.shapes)}. **When:** ${md(r.when)}\n\n**Do instead:** ${md(r.then)}`,
  ).join("\n\n");
  return `---
title: Refusals
---

${GENERATED}

# Refusals an application meets

The errors an application's own code can see — in the frame, or at build —
what each means, and what to do instead. The refusals a host shows a person
when a document cannot be opened are a different list, in the [host
bridge](/docs/host-bridge#refusal-reasons-glossary).

${entries}
`;
}

function shapesPart() {
  const questions = SHAPE_DECISION.map(
    (step, index) => `${index + 1}. ${md(step.ask)}\n   - **Yes:** ${md(step.yes)}\n   - **No:** ${md(step.no)}`,
  ).join("\n");
  const shapes = SHAPES.map(
    (s) =>
      `### ${s.title} {#${s.id}}\n\n${md(s.who)}\n\n` +
      `- **Declare:** ${md(s.declares)}\n` +
      `- **What the runtime does:** ${md(s.mechanism)}\n` +
      `- **For example:** ${md(s.examples)}.` +
      (s.example ? `\n- **In the repository:** [\`${s.example}\`](${GITHUB.replace("/blob/", "/tree/")}${s.example})` : ""),
  ).join("\n\n");
  return `${GENERATED}

## The two questions

${questions}

## The four shapes

${shapes}
`;
}

function constraintPart(c) {
  return `${GENERATED}

::: info ${c.id}
**${md(c.title)}**

${md(c.rule)}

**Why.** ${md(c.why)}

<small>Applies to ${shapesOf(c.shapes)} · ${enforcementOf(c)} · [${c.id} in Constraints](/docs/constraints#${c.id})</small>
:::
`;
}

/* ---------------------------------------------------------- outputs */

export function outputs() {
  const docs = join(repo, "website", "docs");
  const out = new Map([
    [join(repo, "src", "generated", "examples.ts"), examplesModule()],
    [join(docs, "constraints.md"), constraintsPage()],
    [join(docs, "runtime-api.md"), runtimeApiPage()],
    [join(docs, "schema-reference.md"), schemaPage()],
    [join(docs, "refusals.md"), refusalsPage()],
    [join(docs, "parts", "shapes.md"), shapesPart()],
  ]);
  for (const c of CONSTRAINTS) out.set(join(CONSTRAINT_PARTS, `${c.id}.md`), constraintPart(c));
  return out;
}

/** Fragments on disk that no constraint produces any more — a renamed or removed id. */
function orphans(out) {
  if (!existsSync(CONSTRAINT_PARTS)) return [];
  return readdirSync(CONSTRAINT_PARTS)
    .map((name) => join(CONSTRAINT_PARTS, name))
    .filter((path) => !out.has(path));
}

if (process.argv[1] && resolve(process.argv[1]) === fileURLToPath(import.meta.url)) {
  const out = outputs();
  const rel = (path) => relative(repo, path).replace(/\\/g, "/");
  if (process.argv.includes("--check")) {
    const stale = [...out]
      .filter(([path, text]) => !existsSync(path) || readFileSync(path, "utf8").replace(/\r\n/g, "\n") !== text)
      .map(([path]) => rel(path));
    const extra = orphans(out).map(rel);
    if (stale.length || extra.length) {
      process.stderr.write(
        `Generated documentation is out of date — run node scripts/build-docs.mjs\n` +
          stale.map((p) => `  stale: ${p}\n`).join("") +
          extra.map((p) => `  orphan: ${p}\n`).join(""),
      );
      process.exit(1);
    }
    process.stdout.write(`generated documentation is current (${out.size} files)\n`);
  } else {
    for (const [path, text] of out) {
      mkdirSync(dirname(path), { recursive: true });
      writeFileSync(path, text);
    }
    for (const path of orphans(out)) rmSync(path);
    process.stdout.write(`wrote ${out.size} files\n`);
  }
}
