#!/usr/bin/env node
/**
 * Emits the shell template and bootloader runtime as string constants.
 *
 * A browser-hosted compiler has no `dist/` to read and cannot fetch under the
 * air-gap rules it is building for, so the two text assets `buildContainer`
 * needs are published as an importable module instead.
 *
 * Written directly to `dist/` rather than generated into `src/`: the content is
 * two string literals, so there is nothing to typecheck, and a generated source
 * file would either be committed noise or break a clean checkout's typecheck.
 */
import { readFileSync, writeFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const root = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const dist = resolve(root, "dist");

const template = readFileSync(resolve(dist, "template.html"), "utf8");
const runtime = readFileSync(resolve(dist, "dai-runtime.js"), "utf8");

const header = `// Generated by scripts/embed-assets.mjs. Do not edit.\n`;
const constants =
  `export const CONTAINER_TEMPLATE = ${JSON.stringify(template)};\n` +
  `export const RUNTIME_SOURCE = ${JSON.stringify(runtime)};\n`;

writeFileSync(resolve(dist, "templates.js"), header + constants);

writeFileSync(
  resolve(dist, "templates.cjs"),
  header +
    `"use strict";\n` +
    `Object.defineProperty(exports, "__esModule", { value: true });\n` +
    `exports.CONTAINER_TEMPLATE = ${JSON.stringify(template)};\n` +
    `exports.RUNTIME_SOURCE = ${JSON.stringify(runtime)};\n`,
);

const types =
  header +
  `/** The container shell, with its placeholder comments intact. */\n` +
  `export declare const CONTAINER_TEMPLATE: string;\n` +
  `/** The bundled bootloader runtime, inlined into the shell at compile time. */\n` +
  `export declare const RUNTIME_SOURCE: string;\n`;
writeFileSync(resolve(dist, "templates.d.ts"), types);
writeFileSync(resolve(dist, "templates.d.cts"), types);

const kb = (text) => `${(Buffer.byteLength(text) / 1024).toFixed(1)} KB`;
console.log(
  `[dai] embedded template (${kb(template)}) and runtime (${kb(runtime)}) -> dist/templates.js`,
);
