/** GENERATED by scripts/build-confusables.mjs. The UTS #39 table every host loads, by content hash. */
export const CONFUSABLES_ID = "bd086572";
export const CONFUSABLES_UNICODE = "17.0.0";
export const CONFUSABLES_FILE = `confusables.${CONFUSABLES_ID}.json`;
